enabled: true
etcd:
  enabled: false
deployment:
  mode: decoupled
  role: "data_plane"
  role_data_plane:
    config_provider: control_plane
    control_plane:
      host:
          - http://apisix-control:9280
      prefix: /apisix
      timeout: 30
externalEtcd:
  host:
    - "http://apisix-etcd.apisix.svc.cluster.local:2379"
  prefix: "/apisix"
  timeout: 30
  username: "root"
  existingSecret: "apisix-etcd-root"
  secretPasswordKey: "root-password"
  tls:
    enabled: true
    existingSecret: "etcd-crt-secret"
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    caFilename: "ca.crt"
    sni: apisix-etcd.apisix.svc.cluster.local

fullnameOverride: "apisix-dp"

apisix:
  enableIPv6: false
  enableHTTP2: true
  enableServerTokens: true
  setIDFromPodUID: false

  deployment:
    mode: decoupled
    role: "data_plane"
    role_data_plane:
      config_provider: control_plane
      control_plane:
        host:
            - http://apisix-control:9280
        prefix: /apisix
        timeout: 30

  ssl:
    enabled: false

  admin:
    enabled: false
     
  discovery:
    enabled: false
        
  plugins:
    - openid-connect
    - prometheus
    - cors
    - ip-restriction
    - limit-count
    - limit-req

  customPlugins: 
    enabled: false
    luaPath: "/opts/custom_plugins/?.lua"
    plugins: []
    
dashboard:
  enabled: false

ingress-controller:
  enabled: false

podDisruptionBudget:
  enabled: false
resources: {}
nodeSelector: {}
timezone: ""

autoscaling:
  enabled: false

serviceAccount:
  create: false

rbac:
  create: false

discovery:
    enabled: true
vault:
  enabled: false
prometheus:
  enabled: false
extPlugin:
  enabled: false
wasm:
  enabled: false

