{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demoagent-api-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demoagent-api.labels" . | nindent 4 }}
rules:
  - apiGroups: ["demo.disasterproject.com"]
    resources: ["demoagents"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demoagent-api-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demoagent-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demoagent-api-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}